---
title: "NEID Solar Data -- Linear Modeling"
author: "Joe Salzer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(readxl)
library(lme4)
library(MASS)
library(gridExtra)
library(car)
library(glmnet)
```

```{r}
## Data directory
wd_data = "/Users/josephsalzer/research/exostat/"
```

# Loading data

```{r}
final_fits = tibble( read.csv(str_c(wd_data, "final_fits_6kmps.csv") ) ) %>%
  rename( wavelength = lambda ) %>%
  mutate( obs_date = factor(obs_date), wavelength = round(wavelength,3) ) %>%
  mutate( lambda = factor(wavelength), order_idx = factor(order_idx) ) 
final_fits
```

REMOVE OUTLIER LINES

```{r}
final_fits = final_fits %>%
  filter(lambda != 4662.822)
```

# standardize final_fits

standardize final_fits (except for b1, lambda,order_idx,obs_date, and repeat_order)

```{r}
# scale non-categorical variables and non-b1
scaled_final_fits = cbind(
  final_fits %>% dplyr::select(c(b1,lambda,wavelength,order_idx,obs_date,repeat_order)),
  
  final_fits %>%
    dplyr::select(!c(b1,lambda,wavelength,order_idx,obs_date,repeat_order)) %>%
    scale() %>%
    as_tibble()
)
```

```{r}
# convert lambda, date, and order_idx to factors remove repeat_orders
# also create column of centered rv by lambda 
scaled_final_fits = scaled_final_fits %>%
  dplyr::select(!c(repeat_order))
```



# load predictions

```{r}
# read pred.df
pred.df = read.csv(str_c(wd_data, "neid_solar/cv_pred.csv"))
```

```{r}
pred.df
```
```{r}
# create factors out of categories and create a pred error column
pred.df = pred.df %>%
  rename(wavelength = lambda) %>%
  mutate(lambda = factor( round(wavelength,3) ), obs_date = factor(obs_date), order_idx = factor(order_idx)  ) %>%
  mutate(pred_error = true_rv - pred_rv)
```

```{r}
# quantiles of errors
err.quantiles = quantile(pred.df$pred_error, probs = c(.05, .25, .5, .75, .95))
err.quantiles
```

```{r}
# dataframe of tails (5% and 95%) of predictions
tail.df = pred.df %>% 
  filter(pred_error < err.quantiles[1] | pred_error > err.quantiles[5])
```

```{r}
# put b1 values in tail.df and make factors out of obs date and order
tail.df = tail.df %>%
  left_join(final_fits %>% dplyr::select(lambda,obs_date,order_idx,b1))
tail.df
```

Which lambdas appear in tail more than 150 times:
```{r}
bad_lams = ( tail.df %>% group_by(lambda) %>% summarize(n = n()) %>% filter(n > 150) )$lambda
bad_lams 
```

# b1 investigation

## visuals

```{r}
final_fits %>%
  drop_na() %>%
  ggplot() +
  geom_point(mapping = aes(x = snr, y = b1, color = wavelength))
```

```{r}
final_fits %>%
  drop_na() %>%
  ggplot() +
  geom_point(mapping = aes(x = snr, y = b1, color = order_idx))
```


Some "tail" lines b1 v. snr:
```{r}
final_fits %>%
  filter(lambda %in% bad_lams) %>%
  drop_na() %>%
  ggplot() +
  geom_point(mapping = aes(x = snr, y = b1, color = order_idx))
```

```{r}
final_fits %>%
  filter(lambda %in% bad_lams) %>%
  drop_na() %>%
  ggplot() +
  geom_point(mapping = aes(x = snr, y = b1, color = wavelength))
```


```{r}
tail.df %>%
  drop_na() %>%
  ggplot() +
  geom_point(mapping = aes(x = snr, y = b1, color = wavelength))
```

```{r}
tail.df %>%
  filter(wavelength >= 9000)
```







```{r}
tail.df %>%
  mutate(obs_date = factor(obs_date), obs_date = factor(obs_date), order_idx = factor(order_idx)) %>%
  left_join(final_fits %>% dplyr::select(lambda,obs_date,order_idx,b1)) %>%
  #summarize(mean_b1 = mean(b1),sd_b1 = sd(b1))
  ggplot(mapping  = aes(x = b1)) + geom_histogram()
```

```{r}
final_fits %>%
  #summarize(mean_b1 = mean(b1),sd_b1 = sd(b1))
  ggplot(mapping  = aes(x = b1)) + geom_histogram()
```





## linear models

```{r}
b1.lm = lm(b1 ~  snr + depth1 + width1 + a1 + lambda + order_idx + obs_date, scaled_final_fits)
```


```{r}
scaled_final_fits %>%
  filter(lambda == 4116.085) %>%
  summarize(m_b1 = mean(b1))
```

```{r}
summary(b1.lm)
```


```{r}
# dataframe of coefficients
coef.df = tibble( coef = rownames(summary(b1.lm)$coefficients),
                  estimate = summary(b1.lm)$coefficients[,1],
                  se = summary(b1.lm)$coefficients[,2],
                  pval = summary(b1.lm)$coefficients[,4] )
```

```{r}
# non fixed effects coefficients
coef.df %>%
  filter( !startsWith( coef, "obs_date"), !startsWith( coef, "lambda"), !startsWith( coef, "order_idx")  )
```

```{r}
coef.df %>% filter( startsWith( coef, "obs_date") ) %>%
  ggplot(mapping = aes(x = coef)) +
  geom_point(aes(y = estimate)) +
  theme(axis.text.x = element_blank(), axis.ticks = element_blank() ) +
  geom_errorbar(aes(ymin = estimate - 1.96*se, ymax = estimate + 1.96*se)) +
  geom_hline(yintercept = 0, color = "red")
```


```{r}
coef.df %>% filter( startsWith( coef, "lambda") ) %>%
  ggplot(mapping = aes(x = coef)) +
  geom_point(aes(y = estimate)) +
  theme(axis.text.x = element_blank(), axis.ticks = element_blank() ) +
  geom_errorbar(aes(ymin = estimate - 1.96*se, ymax = estimate + 1.96*se)) +
  geom_hline(yintercept = 0, color = "red")
```


