---
title: "NEID Solar Data -- Clean Data"
author: "Joe Salzer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#library(tidyverse)
#library(stringr)
#library(rhdf5)
source("readSpectra.R")
```

```{r}
## Data directory
wd_data = "/Users/josephsalzer/research/exostat/line_property_files/"
```

# read data

## join all files

```{r}
# list of files in line_property_files
files = list.files("line_property_files")

# sample random 5 from files
files = sample(list.files("line_property_files") ,5)
```

```{r}
# create an empty list to store datasets
dataset_list = list()
# start time
START_TIME = Sys.time()

for (i in 1:length(files) ) {
  
  # read file,  loadLineShape returns a list containing the line shape info as well as the template line and hg-reconstructed 
  # if it failed to load the file then it returns a string called "failed"
  loaded_lineshape = loadLineShape(files[i])
  
  # go to next if it failed to load
  if ( any( is.na( loaded_lineshape$line.df ) )  ) {
    print("NA present, skip to next index")
    print(i)
    next
  }
  
  # store loaded_lineshape$line.df into dataset list
  dataset_list[[i]] = loaded_lineshape$line.df
}

# combine all df into a single df
final_df = do.call(rbind, dataset_list)
# write to csv
write_csv(final_df, "/Users/josephsalzer/research/exostat/completeLines2.csv")
# remove files
rm(dataset_list)
# end time
end.time = Sys.time()
# print
print(end.time - START_TIME)
```

# summaries

```{r}
# read data
final_df = read_csv("/Users/josephsalzer/research/exostat/completeLines2.csv")
```


```{r}
summary(final_df)
```

910 line-orders
345 days

```{r}
all( ( final_df %>% count(date) )$n == 910 )

all( ( final_df %>% count(line_order) )$n == 345 )
```


# lines with constant b1 and width 

```{r}
covars = c("fit_gauss_a", "fit_gauss_b", "fit_gauss_depth", "fit_gauss_sigmasq", "rv_template_0.5", "hg_coeff_0", "hg_coeff_1", "hg_coeff_2", "hg_coeff_3", "hg_coeff_4", "hg_coeff_5", "hg_coeff_6", "hg_coeff_7", "hg_coeff_8", "hg_coeff_9", "hg_coeff_10")
```

Some lines have constant (sd of exactly 0) values for b and sigmasq:

```{r}
sd.df = final_df %>%
  group_by(line_order) %>%
  summarize_at(covars, sd) %>%
  filter_at(covars, any_vars(. == 0) ) %>%
  dplyr::select(line_order, fit_gauss_b, fit_gauss_sigmasq)
sd.df
```

```{r}
constantLines = sd.df$line_order
```

```{r}
final_df %>%
  filter(line_order %in% constantLines) %>%
  group_by(line_order) %>%
  summarize(b = mean(fit_gauss_b),
            width = mean(fit_gauss_sigmasq)) %>%
  filter(b != .7 & b != -.7)
```

```{r}
outlier.lines2 = (final_df %>% filter(fit_gauss_b == .7 | fit_gauss_b == -.7) %>% count(line_order))$line_order
```





