---
title: "NEID Solar Data -- v2 data"
author: "Joe Salzer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(MASS)
library(rhdf5)
```

```{r}
## Data directory
wd_data = "/Users/josephsalzer/research/exostat/"
```

# Loading data

## solar_spectrum

```{r}
# download solar spectrum, with flux, flux_norm, lambda, var, and var_norm
# (pixels,order_idx)
solar_spectrum = H5Fopen(str_c(wd_data, "solar_spectrum_ex.h5"))
solar_spectrum
```

*flux norm*
some earlier orders have flux values and later ones dont, this okay?
```{r}
solar_spectrum$flux_norm[1:6,1:10]
```

```{r}
# number of pixels and orders
num_pixels = dim(solar_spectrum$flux)[1]
num_orders = dim(solar_spectrum$flux)[2]
```

```{r}
# vector of orders and pixels
orders = seq(1,num_orders) %>% map_chr( \(x) str_c("order",x) )
pixels = seq(1,num_pixels)
```

```{r}
# create dataframe for orders and pixels
solar_spectrum.df = expand_grid(order = orders, pixel = pixels)
# set columns
solar_spectrum.df$flux_norm = as.vector(solar_spectrum$flux_norm)
solar_spectrum.df$flux = as.vector(solar_spectrum$flux)
solar_spectrum.df$lambda = as.vector(solar_spectrum$lambda)
solar_spectrum.df$var = as.vector(solar_spectrum$var)
solar_spectrum.df$var_norm = as.vector(solar_spectrum$var_norm)
```

```{r}
# remove some vectors
rm(orders, pixels, num_orders, num_pixels)
```

```{r}
solar_spectrum.df
```

## pixel lines

```{r}
#line_name = "line_5236.09361_57.h5"

#line_name = "line_6126.72717_74.h5"

line_name = "line_9864.45699_112.h5"
```

```{r}
# download a single line
# (pixels,date)
single_line = H5Fopen(str_c(wd_data, line_name))
single_line
```
```{r}
single_line$pixels
single_line$order_idx
single_line$fit_lambdac
```

```{r}
# vector of dates
dates = single_line$dates
# vector of pixels
pixels = as.numeric( str_split_1(single_line$pixels,":") )
pixels = seq(pixels[1],pixels[2])
```

```{r}
# create dataframe for dates and pixels
single_line.df = expand_grid(date = dates, pixel = pixels )
# set columns
single_line.df$flux = as.vector( single_line$flux)
single_line.df$flux_norm = as.vector( single_line$flux_norm)
single_line.df$lambda = as.vector( single_line$lambda) 
single_line.df$var = as.vector( single_line$var)
single_line.df$var_norm = as.vector( single_line$var_norm) 
```

```{r}
rm(dates, pixels)
```

## summaries

```{r}
solar_spectrum.df %>% filter(order == "order57",pixel == 2491)
```

```{r}
single_line.df %>% filter(pixel == 2491)
```
2021-06-20 is the date for solar_spectrum

# Figures

## solar spectrum

###flux (or flux norm) by lambda for a given order
```{r}
solar_spectrum.df %>%
  filter(order == "order52") %>%
  ggplot(mapping = aes(x = lambda, y = flux)) +
  geom_point()
```

```{r}
solar_spectrum.df %>%
  filter(order == "order52") %>%
  ggplot(mapping = aes(x = lambda, y = flux_norm)) +
  geom_point()
```


### line file on the spectrum

```{r}
# lower and upper pixel
pixel_lower = as.numeric( str_split_1(single_line$pixels,":")[1] )
pixel_upper = as.numeric( str_split_1(single_line$pixels,":")[2] )

ordernum = str_c("order",single_line$order_idx)
```

```{r}
solar_spectrum.df %>%
  filter(order == ordernum,
         pixel >= pixel_lower - 50,
         pixel <= pixel_upper + 50) %>%
  ggplot(mapping = aes(x = lambda, y = flux_norm)) +
  geom_vline(xintercept = (solar_spectrum.df %>% filter(order == ordernum,
                                                        pixel == pixel_lower))$lambda) +
  geom_vline(xintercept = (solar_spectrum.df %>% filter(order == ordernum,
                                                        pixel == pixel_upper))$lambda) +
  geom_point()
```

```{r}
rm(pixel_lower, pixel_upper, ordernum)
```

## single line


```{r}
single_line.df%>%
  #mutate(date = as.Date(date), date = as.numeric(date)) %>%
  filter(date == "2021-06-20") %>%
  ggplot(mapping = aes(x = pixel, y = flux_norm, color = date)) +
  geom_point()
```

```{r}
single_line.df%>%
  mutate(date = as.Date(date)) %>%
  ggplot(mapping = aes(x = date, y = flux_norm, color = pixel)) +
  geom_point()
```



```{r}

```


