---
title: "NEID Solar Data -- Other Modeling"
author: "Joe Salzer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(keras) 
library(caret)
```

```{r}
## Data directory
wd_data = "/Users/josephsalzer/research/exostat/neid_solar/"
```


# Loading data

```{r}
# load data without lam_c1, repeat_order, or gh1 measurements
final_fits = tibble( read.csv(str_c(wd_data, "final_fits.csv") ) ) %>%
  mutate(obs_date = as.Date(obs_date)) %>%
  select(!c(lam_c1,repeat_order, gh_1, sigma_gh_1, tgh_1, sigma_tgh_1))
  #mutate(lambda = factor(lambda), order_idx = factor(order_idx))
final_fits
```

# naive numerical lambda;dropping order_idx and obs_date

```{r}
df = final_fits %>% select(!c(order_idx,obs_date))
df = cbind( df %>% select(rv), df %>% select(!rv) %>% scale()  )
df
```

```{r}
set.seed(123)
#use 70% of dataset as training set and 30% as test set
sample = sample(c(TRUE, FALSE), nrow(df), replace=TRUE, prob=c(0.7,0.3))
train = df[sample, ]
test = df[!sample, ]
```

```{r}
x_train = train %>% select(!rv)
y_train = train %>% select(rv)
x_test = test %>% select(!rv)
y_test = test %>% select(rv)
```


