---
title: "NEID Solar Data -- PCA"
author: "Joe Salzer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("readSpectra.R")
library(car)
library(ggpubr)
#library(plotly)
library(GGally)
library(Matrix)
```

```{r}
## Data directory
wd_data = "/Users/josephsalzer/research/exostat/"
```

# Loading data

```{r}
# read data
final.df = read_csv("/Users/josephsalzer/research/exostat/completeLines.csv")
```

```{r}
colnames(final.df)
```




*REMOVING SOME PROBLEMATIC ORDERS:*
```{r}
# final.df = final.df %>%
#   filter( !(order_idx %in% c(56,57,58)) )
```


*REMOVING BF/AF BIASED LINES:*
```{r}
# final.df = final.df %>%
#   filter( (line_order %in% lowPClines) )
# final.df
```



```{r}
# convert line order and date into factors
final.df = final.df %>%
  mutate(line_order = factor(line_order),
         date = as.Date(date))
```

```{r}
# list of lambdas in final.df
final.lines = ( final.df %>% group_by(lambdac_vald) %>% summarize(n. = n()) )$lambdac_vald
length(final.lines)
```

```{r}
# list of lamb-orders in model.df
final.line_order = ( final.df %>% group_by(line_order) %>% summarize(n. = n()) )$line_order
length(final.line_order)
```

```{r}
# list of lambda-orders in model.df
final.days = ( final.df %>% group_by(date) %>% summarize(n. = n()) )$date
length(final.days)
```

# PCA

## PCA on RV data



```{r}
rv.df = final.df %>%
  #filter(date_groups == 2) %>%
  select(rv_template_0.5, date, line_order) %>%
  pivot_wider(names_from = line_order, values_from = rv_template_0.5)
head(rv.df)
```

```{r}
rankMatrix( rv.df %>% select(!date) )
```

*ADDING PLANERTARY SIGNAL IS LIKE ADDING A RANK 1 MATRIX TO OUR LINES*

```{r}
# rv.df = injectPlanet(final.df, 5) %>% 
#   select(pert_rv, date, line_order) %>%
#   pivot_wider(names_from = line_order, values_from = pert_rv)
# head(rv.df)
```

```{r}
# # the value for each day to perturb the line by
# pert_val = 5*sin( (2*pi/366)*changeFun( as.numeric(rv.df$date) ))
# # number of lines
# num_lines = 910
# # matrix to perturb the og dataframe by
# pert_mat = pert_val %*% t(rep(1,num_lines))
```

```{r}
# rv.df  = ( rv.df %>% select(!date) ) + pert_mat
```

```{r}
# pert_mat[1:5,1:5]
```

```{r}
# dim(rv.df)
```



*RUN PCA*


```{r}
# run pca with scaling
rv.pca = prcomp(rv.df %>% select(!date), center = T, scale = T, retx = T)
```

```{r}
#calculate total variance explained by each principal component
var_explained = rv.pca$sdev^2 / sum(rv.pca$sdev^2)
head(var_explained)
```

```{r}
sum(var_explained[1:100])
```
```{r}
ggplot(mapping = aes(x = c(1:length(var_explained)),y = var_explained)) +
  geom_line() +
  geom_point() +
  xlab("Principal Component") + 
  ylab("Variance Explained") +
  xlim(0,50)
```

```{r}
pc1_plot = cbind(rv.df, rv.pca$x[,1:6]) %>%
  ggplot() +
  geom_point(mapping = aes(x = date, y = PC1), size = .5)
pc2_plot = cbind(rv.df, rv.pca$x[,1:6]) %>%
  ggplot() +
  geom_point(mapping = aes(x = date, y = PC2), size = .5)
pc3_plot = cbind(rv.df, rv.pca$x[,1:6]) %>%
  ggplot() +
  geom_point(mapping = aes(x = date, y = PC3), size = .5)
pc4_plot = cbind(rv.df, rv.pca$x[,1:6]) %>%
  ggplot() +
  geom_point(mapping = aes(x = date, y = PC4), size = .5)
pc5_plot = cbind(rv.df, rv.pca$x[,1:6]) %>%
  ggplot() +
  geom_point(mapping = aes(x = date, y = PC5), size = .5)
pc6_plot = cbind(rv.df, rv.pca$x[,1:6]) %>%
  ggplot() +
  geom_point(mapping = aes(x = date, y = PC6), size = .5)

pc7_plot = cbind(rv.df, rv.pca$x[,1:7]) %>%
  ggplot() +
  geom_point(mapping = aes(x = date, y = PC7), size = .5)
pc8_plot = cbind(rv.df, rv.pca$x[,1:8]) %>%
  ggplot() +
  geom_point(mapping = aes(x = date, y = PC8), size = .5)
```

*PC scores*

```{r}
p = ggarrange(plotlist = list(pc1_plot, pc2_plot,
                              pc3_plot, pc4_plot,
                              pc5_plot, pc6_plot), nrow = 3, ncol = 2)
p
```

```{r}
#ggsave("pc_plots_small.pdf", width = 10, height = 5)
```

```{r}
# dataframe of PC directions (across lines)
pcDir_df = data.frame(
  lineID = names( rv.pca$rotation[,1] ),
  PC1_dir = unname( rv.pca$rotation[,1] ),
  PC2_dir = unname( rv.pca$rotation[,2] ),
  PC3_dir = unname( rv.pca$rotation[,3] ),
  PC4_dir = unname( rv.pca$rotation[,4] ),
  PC5_dir = unname( rv.pca$rotation[,4] ),
  PC6_dir = unname( rv.pca$rotation[,6] )
)
pcDir_df$wavelength = as.numeric(str_split_i(pcDir_df$lineID, "_",1))
pcDir_df
```

*PC directions*
```{r}
pc1_plot = pcDir_df %>%
  ggplot() +
  geom_point(mapping = aes(x = lineID, y = PC1_dir ), size = .5) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
pc2_plot = pcDir_df %>%
  ggplot() +
  geom_point(mapping = aes(x = lineID, y = PC2_dir ), size = .5) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
pc3_plot = pcDir_df %>%
  ggplot() +
  geom_point(mapping = aes(x = lineID, y = PC3_dir ), size = .5) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
pc4_plot = pcDir_df %>%
  ggplot() +
  geom_point(mapping = aes(x = lineID, y = PC4_dir ), size = .5) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
pc5_plot = pcDir_df %>%
  ggplot() +
  geom_point(mapping = aes(x = lineID, y = PC5_dir ), size = .5) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
pc6_plot = pcDir_df %>%
  ggplot() +
  geom_point(mapping = aes(x = lineID, y = PC6_dir ), size = .5) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
```

```{r}
p = ggarrange(plotlist = list(pc1_plot, pc2_plot,
                              pc3_plot, pc4_plot,
                              pc5_plot, pc6_plot), nrow = 3, ncol = 2)
p
```

```{r}
ggsave("pc_dir_plots_small.pdf", width = 10, height = 5)
```



plots of pc directions for each line
```{r}
ggpairs(pcDir_df, columns = 2:5)
```

```{r}
pcDir_df %>%
  ggplot() +
  geom_point(mapping = aes(x = PC2_dir, y = PC4_dir), size = .5)
```



```{r}
# plots some lines of various pc directions
sampleLines = pcDir_df %>%
  filter( abs(PC1_dir) < .02,
          abs(PC4_dir) < .05) %>%
  pull(lineID)

length(sampleLines)

final.df %>%
  filter(line_order %in% sample(sampleLines,4)) %>%
  ggplot() +
  geom_point(mapping = aes(x = date, y = rv_template_0.5), size = .5) +
  facet_wrap(~line_order, scales = "free")
```



```{r}
# "low" PC lines close to zero
lowPClines = pcDir_df %>%
  filter(abs(PC1_dir) < .02) %>%
  pull(lineID)
length(lowPClines)

final.df %>%
  filter(line_order %in% sample(lowPClines,4) ) %>%
  ggplot() +
  geom_point(mapping = aes(x = date, y = rv_template_0.5), size = .5) +
  facet_wrap(~line_order, scales = "free")
```


```{r}
saveRDS(lowPClines, file = "nonbiasedLines.rds")
```

```{r}
# "low" PC lines close to zero
lowPClines = pcDir_df %>%
  filter(PC1_dir < .02, PC1_dir > -.02,
         PC2_dir < .025, PC2_dir > -.025,
         PC3_dir < .05, PC3_dir > -.05,
         PC4_dir < .05, PC4_dir > -.05) %>%
  pull(lineID)
length(lowPClines)

final.df %>%
  filter(line_order %in% sample(lowPClines,4) ) %>%
  ggplot() +
  geom_point(mapping = aes(x = date, y = rv_template_0.5), size = .5) +
  facet_wrap(~line_order, scales = "free")
```


















DEPTHS
with all days
```{r}
# dataframe where each row is a date, and there are columns for the line orders
rv.df = final.df %>%
  select(fit_gauss_sigmasq, date, line_order) %>%
  pivot_wider(names_from = line_order, values_from = fit_gauss_sigmasq)

# to scale or not
rv.pca = prcomp(rv.df %>% select(!date), center = T, scale = T, retx = T)

cbind(rv.df, rv.pca$x[,1:10]) %>%
  ggplot() +
  geom_point(mapping = aes(x = date, y = PC3))
```








