---
title: "NEID Solar Data -- loading raw spectra"
author: "Joe Salzer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(rhdf5)
source("readSpectra.R")
```

```{r}
## Data directory
wd_data = "/Users/josephsalzer/research/exostat/line_property_files/"
```

# testing load.lineshape

```{r}
# list of files in line_property_files
file.list = list.files("line_property_files")
head(file.list)
```


```{r}
# line index
i = 200
#i = match("line_4294.74364_31_fit.h5",file.list)

file.list[i]
```



```{r}
# open one file
line.h5 = H5Fopen(str_c(wd_data, "line_4971.29883_50_fit.h5"))
# see names, datatype and dim of line.h5
name.df = h5ls(line.h5)
value.list = h5dump(line.h5)
name.df
```

```{r}
loadedLineShape = load.lineshape(file.list[i])
```



```{r}
value.list$blend_RV_factor
```

```{r}
ggplot() +
  geom_point(mapping = aes(x = value.list$template_lambda,y=value.list$template_flux)) +
  geom_line(mapping = aes(x = value.list$template_lambda,y=value.list$tgh_reconstruct[,1]), color = "red") +
  geom_line(mapping = aes(x = value.list$template_lambda,y=value.list$tgh_reconstruct[,40]), color = "blue")
  #geom_line(mapping = aes(x = value.list$template_lambda,y=value.list$gh_reconstruct[,1]), color = "blue")
```

# testing train_test_standardize

```{r}
# read data
final.df = read_csv("/Users/josephsalzer/research/exostat/completeLines.csv")
```

```{r}
# covariates
covars = c("fit_gauss_a", "fit_gauss_b", "fit_gauss_depth", 
             "fit_gauss_sigmasq", "hg_coeff_0", "hg_coeff_1", 
             "hg_coeff_2", "hg_coeff_3", "hg_coeff_4", 
             "hg_coeff_5", "hg_coeff_6", "hg_coeff_7", 
             "hg_coeff_8", "hg_coeff_9", "hg_coeff_10")

# covars we want to do PCA on
covars.pca = c("hg_coeff_0", "hg_coeff_1", "hg_coeff_2", "hg_coeff_3", "hg_coeff_4", "hg_coeff_5", "hg_coeff_6", "hg_coeff_7", "hg_coeff_8", "hg_coeff_9", "hg_coeff_10")
```

```{r}
# load in current data frame
select.df = final.df %>% select( all_of(c("rv_template_0.5","line_order","date",covars)) )
```

                              
```{r}
standardized = train_test_standardize(current.df = select.df,
                                      covars = covars,
                                      covars.pca = NULL,
                                      testIndex = c(1,2),
                                      responseChange = T,
                                      trainTestSplit = T)
```

```{r}
standardized$test.df
```










