---
title: "NEID Solar Data -- loading files"
author: "Joe Salzer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("readSpectra.R")
```

# Loading data

```{r}
# working directory
wd = "/Users/josephsalzer/research/exostat/"
```

change working directory to wherever raw_spectrum_files and line_property_files is located

## file lists

```{r}
# list of files in raw_spectrum_files
raw_spectrum_file_list = list.files(str_c(wd,"raw_spectrum_files"), pattern = ".h5")
```

```{r}
# list of solar spectrum files
solarspectrum_list = raw_spectrum_file_list[!is.na( str_extract(raw_spectrum_file_list,"solar_spectrum") )]
# get dates for solar spectrum
all_dates = str_sub( str_split_fixed(solarspectrum_list,"_",n=3)[,3], end = -4 )
```

```{r}
# list of line files
line_list = raw_spectrum_file_list[!is.na( str_extract(raw_spectrum_file_list,"line") )]
# get line-orders 
all_lineorders = str_sub( str_split_fixed(line_list,"_",n=2)[,2], end = -4 )
```

```{r}
# list of line property files
lineProp_list = list.files(str_c(wd,"line_property_files"), pattern = ".h5")
# get line-orders, from line property (shape) files
all_lineorders_prop = str_sub( str_split_fixed(lineProp_list,"_",n=2)[,2], end = -8 )
```

```{r}
# list of line property files
bisector_list = list.files(str_c(wd,"bisector"), pattern = ".h5")
```

## summaries

```{r}
# number of spectra
length(solarspectrum_list)
# number of lines within spectra
length(line_list)
# number of lines from line property files
length(all_lineorders_prop)
```

# read solar spectra

```{r}
# example solar spectrum
solarspectrum_list[1]
spectra_df = loadSolarFile(solarspectrum_list[1], wd_data = str_c(wd,"raw_spectrum_files/"))
```

```{r}
summary( spectra_df )
```

```{r}
# single order
spectra_df %>%
  filter(order == 63) %>%
  ggplot() +
  geom_point(mapping = aes(x = lambda, y = flux_norm), size = .2)
```

```{r}
NUM_SAMPLES_TEMPLATE = 5000

# single order
temp_df = spectra_df %>%
  filter(order == 76,
         lambda < 6250,
         lambda > 6240)

# fit a weighted spline to the template
smooth_fit_template = smooth.spline(x = temp_df$lambda, y = temp_df$flux_norm, w = 1/temp_df$var)
# lower and upper wavelength from template
wavelength_lower = min(temp_df$lambda)
wavelength_upper = max(temp_df$lambda)
# get samples of the smoothed spline from the first wavelength in the dataframe to the last
wavelength_grid_template = seq(wavelength_lower,
                               wavelength_upper,
                               length.out = NUM_SAMPLES_TEMPLATE )
fit_grid_template = predict(smooth_fit_template, wavelength_grid_template)
```

```{r}
ggplot() +
  geom_line(mapping = aes(x = fit_grid_template$x, y = fit_grid_template$y), linewidth = .6) +
  ylab("Normalized Flux") +
  xlab("Wavelength") +
  theme_classic() +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 20))
ggsave("visuals/spectra_example.png", width = 6.8, height = 3)
```



```{r}
rm(spectra_df)
```

# read single line

```{r}
# example line
i = 100
line_df = loadLineFile( line_list[i], wd_data = str_c(wd,"raw_spectrum_files/") )
```

time series of pixels
```{r}
line_df %>%
  filter(pixel %in% c(2911,2912,2913)) %>%
  ggplot() +
  geom_point(mapping = aes(x = date, y = flux_norm, color = pixel))
```


```{r}
summary( line_df )
```


```{r}
line_df %>%
  filter(date %in% sample(all_dates, 3) ) %>%
  ggplot() +
  geom_point(mapping = aes(x = pixel, y = flux_norm, color = factor(date) ), size = .5)
```

```{r}
line_df %>%
  filter(date %in% sample(all_dates, 3),
         lambda < 3895.8,
         lambda > 3895.4) %>%
  ggplot() +
  geom_point(mapping = aes(x = pixel, y = flux_norm, color = factor(date) ), size = .7) +
  geom_line(mapping = aes(x = pixel, y = flux_norm, color = factor(date) ), alpha = .5)
```
core part of the line is around 2940 - 2970
```{r}
rm(line_df)
```



# read a single line's property files

```{r}
# read a line's property file in
i = 101

lineProp_list[i]
single_lineprop = loadLineShape(lineProp_list[i], wd_data = str_c(wd,"line_property_files/"))
```

## template

```{r}
single_lineprop$template.df %>%
  ggplot() +
  geom_point(mapping = aes(x = lambda, y = flux))
```


## hg reconstructed

```{r}
single_lineprop$reconstruct.df %>%
  select(date, starts_with("gh")) %>%
  pivot_longer(!date, names_to = "gh_pixel", values_to = "flux") %>%
  mutate(pixel = as.numeric(str_split_fixed(gh_pixel,"\\.",2)[,2]) ) %>%
  filter(date %in% sample(all_dates, 3)) %>%
  ggplot() +
  geom_point(mapping = aes(x = pixel, y = flux, color = date), size = .5) +
  geom_line(mapping = aes(x = pixel, y = flux, color = date ), alpha = .5)
```

```{r}
single_lineprop$reconstruct.df %>%
  select(date, starts_with("tgh")) %>%
  pivot_longer(!date, names_to = "gh_pixel", values_to = "flux") %>%
  mutate(pixel = as.numeric(str_split_fixed(gh_pixel,"\\.",2)[,2]) ) %>%
  filter(date %in% sample(all_dates, 3)) %>%
  ggplot() +
  geom_point(mapping = aes(x = pixel, y = flux, color = date), size = .5) +
  geom_line(mapping = aes(x = pixel, y = flux, color = date ), alpha = .5)
```

## line property

```{r}
head(single_lineprop$line.df)
```

# project template onto gh

```{r}
# read a line's property file in
i = 100

lineProp_list[i]
single_lineprop = loadLineShape(lineProp_list[i], wd_data = str_c(wd,"line_property_files/"))
temp_df = single_lineprop$line.df
```

```{r}
template_deriv_onto_gh = H5Fopen("project_template/project_template_deriv_onto_gh.h5")
template_deriv_onto_gh
```


```{r}
# index of template_deriv_onto_gh that matches this file name
template_deriv_onto_gh_ID = which(str_sub(lineProp_list[i], end = -8) == str_sub(template_deriv_onto_gh$filename, end = -4))
template_deriv_onto_gh_ID
```

```{r}
template_deriv_onto_gh$gh_vs_mps_coeffs[1:11,,template_deriv_onto_gh_ID]
template_deriv_onto_gh$tgh_vs_mps_coeffs[1:11,,template_deriv_onto_gh_ID]
```


```{r}
# vector showing how a Doppler shift projects onto GH coefficients for a single line
d_gh = template_deriv_onto_gh$gh_vs_mps_coeffs[1:11,2,template_deriv_onto_gh_ID]
d_tgh = template_deriv_onto_gh$tgh_vs_mps_coeffs[1:11,2,template_deriv_onto_gh_ID]
d_gh
d_tgh
```

```{r}
# vector of original GH coefficients for a single line and time
g = ( temp_df %>% select(starts_with("thg")) %>% as.matrix() )[1,]
(g - sum(g*d_tgh)/sum(d_tgh*d_tgh) * d_tgh)[1:6]
# vector of original GH coefficients for a single line and time
g = ( temp_df %>% select(starts_with("thg")) %>% as.matrix() )[2,]
(g - sum(g*d_tgh)/sum(d_tgh*d_tgh) * d_tgh)[1:6]
# vector of original GH coefficients for a single line and time
g = ( temp_df %>% select(starts_with("thg")) %>% as.matrix() )[3,]
(g - sum(g*d_tgh)/sum(d_tgh*d_tgh) * d_tgh)[1:6]
```

```{r}
# vector of original GH coefficients for a single line and time
g = ( temp_df %>% select(starts_with("hg")) %>% as.matrix() )[1,]
(g - sum(g*d_gh)/sum(d_gh*d_gh) * d_gh)[1:6]
# vector of original GH coefficients for a single line and time
g = ( temp_df %>% select(starts_with("hg")) %>% as.matrix() )[2,]
(g - sum(g*d_gh)/sum(d_gh*d_gh) * d_gh)[1:6]
# vector of original GH coefficients for a single line and time
g = ( temp_df %>% select(starts_with("hg")) %>% as.matrix() )[3,]
(g - sum(g*d_gh)/sum(d_gh*d_gh) * d_gh)[1:6]
```

for every day at once:

```{r}
# matrix of original GH coefficients for a single line over each time
# T x 11 matrix
HG = ( temp_df %>% select(starts_with("hg")) %>% as.matrix() )
```

```{r}
# find orthogonal, "cleaned" gh coefficients
# each element in the rows of the matrix rep(1,345) %*% t(d) are multiplied by the corresponding element of the vector G %*% d / sum(d*d)
HG_perp = HG - sweep( x = rep(1,345) %*% t(d_gh), MARGIN = 1, STATS = HG %*% d_gh / sum(d_gh*d_gh), FUN = "*")
HG_perp[1:3,1:6]
```

```{r}
# matrix of original GH coefficients for a single line over each time
# T x 11 matrix
THG = ( temp_df %>% select(starts_with("thg")) %>% as.matrix() )
```

```{r}
# find orthogonal, "cleaned" gh coefficients
# each element in the rows of the matrix rep(1,345) %*% t(d) are multiplied by the corresponding element of the vector G %*% d / sum(d*d)
THG_perp = THG - sweep( x = rep(1,345) %*% t(d_tgh), MARGIN = 1, STATS = THG %*% d_tgh / sum(d_tgh*d_tgh), FUN = "*")
THG_perp[1:3,1:6]
```


# bisector

```{r}
i = 100
# line properties
single_lineprop = loadLineShape(lineProp_list[i], wd_data = str_c(wd,"line_property_files/"))
# names 
linePropName = paste0( str_split_1( lineProp_list[i], "_")[1:3], collapse = "_" )
bisectorNames = apply(str_split_fixed(bisector_list, "_", n = 4)[,1:3], 1, function(row) paste(row, collapse = "_"))
which( linePropName == bisectorNames )
```

```{r}
bisector_file = H5Fopen(str_c("bisector/",bisector_list[which( linePropName == bisectorNames )]))
```

```{r}
lineProp_list[i]
bisector_file$lambdac_vald
bisector_file$order_idx

rm(i,linePropName,bisectorNames)
```


```{r}
rv_df = single_lineprop$line.df %>%
  select(date,rv_template_0.5)
```

```{r}
bisector_file$target_depths
```
```{r}
1-bisector_file$target_depths
```

```{r}
bisector_file$bisector[,1:5]
```

```{r}
dim(bisector_file$bisector)
```

```{r}
find_idx_for_target_abs_flux = function( target_fluxes, flux_lo, flux_hi) {
  return(target_fluxes >= flux_lo & target_fluxes <= flux_hi)
}
```

```{r}
bisector_file$bisector[find_idx_for_target_abs_flux(bisector_file$target_depths,0.851,0.95),1:5]

apply(bisector_file$bisector[find_idx_for_target_abs_flux(bisector_file$target_depths,0.851,0.95),1:5],
      MARGIN = 2, FUN = mean)
```

